# Generated by Django 2.1.2 on 2018-12-15 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_nums',
            new_name='click_num',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='favor_nums',
            new_name='favor_num',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='student_nums',
            new_name='student_num',
        ),
    ]
