# Generated by Django 2.1.2 on 2018-12-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='work_years',
            new_name='work_year',
        ),
    ]
