# Generated by Django 2.1.4 on 2019-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Organization description'),
        ),
    ]
