# Generated by Django 2.1.2 on 2018-12-15 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20181214_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='fav_nums',
            new_name='fav_num',
        ),
    ]
