# Generated by Django 2.1.4 on 2019-01-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190103_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('TI', 'Training institution'), ('school', 'School'), ('individual', 'Individual')], default='school', max_length=10, verbose_name='Category'),
        ),
    ]
