# Generated by Django 2.1.2 on 2018-12-15 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20181214_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='click_num',
            field=models.IntegerField(default=0, verbose_name='click number'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='fav_num',
            field=models.IntegerField(default=0, verbose_name='favorite number'),
        ),
    ]
