# Generated by Django 2.1.4 on 2019-01-03 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('1', 'Training institution'), ('2', 'School'), ('3', 'Individual')], default='school', max_length=10, verbose_name='Category'),
        ),
    ]
