# Generated by Django 2.1.4 on 2019-01-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20190104_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='image',
            field=models.ImageField(default='', upload_to='instructor/%Y/%m', verbose_name='Image'),
        ),
    ]
