# Generated by Django 2.1.4 on 2018-12-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20181214_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecomment',
            options={'verbose_name': 'Course Comment', 'verbose_name_plural': 'Course Comments'},
        ),
    ]
