# Generated by Django 2.1.4 on 2018-12-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_type',
            field=models.CharField(choices=[('r', 'Register'), ('f', 'Forget password')], max_length=2, verbose_name='Type'),
        ),
    ]
